routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', 'AdminController@dashboard');


Auth::routes();

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('/reservation', 'AdminController@reservation')->name('reservation');
Route::post('/send_message', 'AdminController@sendmessage')->name('send.message');



Route::group(['prefix' => 'admin', 'middleware' => 'auth',], function () {
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::resource('/slider', 'SliderController');
    Route::get('/delete/{id}', 'AdminController@delete')->name('slider.delete');
    Route::get('/category_delete/{id}', 'AdminController@category_delete')->name('category.delete');
    Route::resource('/category', 'CategoryController');
    Route::get('/item', 'AdminController@item')->name('item.show');
    Route::get('/item_show', 'AdminController@item_show')->name('item.show1');
    Route::post('/add_item', 'AdminController@add_item')->name('item.store');
    Route::get('/reservation_show', 'AdminController@reservation_show')->name('reservation.show');
    Route::POST('/reservation_update/{id}', 'AdminController@updated')->name('reservation.update');
    Route::get('/message', 'AdminController@message')->name('message');
    Route::get('/food_category', 'AdminController@food_category')->name('food.category');
    Route::post('/food_category_add', 'AdminController@food_category_add')->name('category.food');
    Route::get('/food_category_show', 'AdminController@food_category_show')->name('category.show');
    Route::get('/food_item', 'AdminController@food_item')->name('food.item');
    Route::post('/food_item_add', 'AdminController@food_item_add')->name('item.food');
    Route::get('/food_item_show', 'AdminController@food_item_show')->name('item');
});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $fillable = ['title', 'sub_title', 'image',];
}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Slider;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders = Slider::all();
        return view('admin.slider.index', compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.slider.post');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $slider = new Slider;
        [
            'file' => 'max:500000',
        ];
        $slider->title = $request->title;
        $slider->sub_title = $request->sub_title;


        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('/images');
            $image->move($location, $filename);
            $slider->image = $filename;
        }

        $slider->save();
        return Redirect('admin/dashboard')->with('message', 'slider added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/slider/index.blade.php
@extends('layouts.app')
@section('content')
<div class="content">
<center><h1>Slider</h1></center>

<table class="table">
<tr>
    <th>Id</th>
    <th>Title</th>
    <th>Sub-title</th>
    <th>Image</th>
</tr>
@foreach ($sliders as $key=>$slider)
<tr>
    <td>{{ $key+1 }}</td>
    <td>{{ $slider->title }}</td>
    <td>{{ $slider->sub_title }}</td>
    <td><img src="{{ asset('images/'.$slider->image) }}" alt="image" height="80px"></td>
    <td><a href="{{ route('slider.delete',$slider->id) }}" class="btn btn-danger"> Delete</a></td>
</tr>
@endforeach

</table>
</div>

@endsection

resources/views/admin/slider/post.blade.php
@extends('layouts.app')
@section('content')
<div class="content">
<center><h1>Slider Upload</h1></center>

<div class="container">

<form class="form-horizontal" action="{{ route('slider.store')}}" method="post" enctype="multipart/form-data">
    {{csrf_field()}}
  <fieldset>

      <div class="control-group">
        <label class="control-label">Title of Slider</label>
        <div class="controls">
          <input type="text" name="title" placeholder="slider title" required="">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Title of Slider</label>
        <div class="controls">
          <input type="text" name="sub_title" placeholder="slider sub_title" required="">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Slider Image</label>
        <div class="controls">
          <input type="file" name="image" required="">
        </div>
    </div>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Add Slider</button>
      <button type="reset" class="btn">Cancel</button>
    </div>

  </fieldset>
</form>
</div>


</div>

@endsection