routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', 'AdminController@dashboard');


Auth::routes();

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('/reservation', 'AdminController@reservation')->name('reservation');
Route::post('/send_message', 'AdminController@sendmessage')->name('send.message');



Route::group(['prefix' => 'admin', 'middleware' => 'auth',], function () {
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::resource('/slider', 'SliderController');
    Route::get('/delete/{id}', 'AdminController@delete')->name('slider.delete');
    Route::get('/category_delete/{id}', 'AdminController@category_delete')->name('category.delete');
    Route::resource('/category', 'CategoryController');
    Route::get('/item', 'AdminController@item')->name('item.show');
    Route::get('/item_show', 'AdminController@item_show')->name('item.show1');
    Route::post('/add_item', 'AdminController@add_item')->name('item.store');
    Route::get('/reservation_show', 'AdminController@reservation_show')->name('reservation.show');
    Route::POST('/reservation_update/{id}', 'AdminController@updated')->name('reservation.update');
    Route::get('/message', 'AdminController@message')->name('message');
    Route::get('/food_category', 'AdminController@food_category')->name('food.category');
    Route::post('/food_category_add', 'AdminController@food_category_add')->name('category.food');
    Route::get('/food_category_show', 'AdminController@food_category_show')->name('category.show');
    Route::get('/food_item', 'AdminController@food_item')->name('food.item');
    Route::post('/food_item_add', 'AdminController@food_item_add')->name('item.food');
    Route::get('/food_item_show', 'AdminController@food_item_show')->name('item');
});

resources/views/includes/footer.blade.php
<footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="">
                 Resturent 
                </a>
              </li>
              <li>
                <a href="">
                  About Us
                </a>
              </li>
              <li>
                <a href="">
                  Blog
                </a>
              </li>
              <li>
                <a href="">
                  Licenses
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright float-right">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script>, made with <i class="material-icons">favorite</i> by
            <a href=" target="_blank">Asif Iqbal</a> for a better web.
          </div>
        </div>
      </footer>

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">Dashboard</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another Notification</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="dropdown">
                <a class="dropdown-toggle"  id="dropdownMenuButton" data-toggle="dropdown">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                    @if(Auth::user())
                  <a class="dropdown-item" href="">{{ Auth::user()->name }}</a>
                  @else
                  <a class="dropdown-item" href="">User</a>
                  @endif
                  <a class="dropdown-item" href="#">Settings</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{ route('logout') }}"
                  onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                   {{ __('Logout') }}
               </a>

               <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                   @csrf
               </form>
                </div>
              </li>


            </ul>
          </div>
        </div>
      </nav>

resources/views/includes/sidebar.blade.php
<div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
    <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
    <div class="logo">
    <a href="{{route('welcome')}}" class="simple-text logo-normal">
       Resturent Managment
      </a>
    </div>
    <div class="sidebar-wrapper">
      <ul class="nav">
        <li class="nav-item ">
          <a class="nav-link" href="{{ route('dashboard') }}">
            <i class="material-icons">dashboard</i>
            <p>Dashboard</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{{ route('slider.index') }}">
            <i class="material-icons">person</i>
            <p>Slider</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{{ route ('slider.create')}}">
            <i class="material-icons">content_paste</i>
            <p>Upload Slider</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{{ route('category.index') }}">
            <i class="material-icons">library_books</i>
            <p>Category</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{{ route('item.show') }}">
            <i class="material-icons">bubble_chart</i>
            <p>Item</p>
          </a>
        </li>
        <li class="nav-item ">
        <a class="nav-link" href="{{route('reservation.show')}}">
            <i class="material-icons">location_ons</i>
            <p>Reservation</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{{ route('message') }}">
            <i class="material-icons">notifications</i>
            <p>User Message</p>
          </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{{ route('food.category') }}">
              <i class="material-icons">notifications</i>
              <p>Food category</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{{ route('item') }}">
              <i class="material-icons">notifications</i>
              <p>Food Items</p>
            </a>
          </li>

      </ul>
    </div>
  </div>